export interface TableHeader {
  col_name: string;
  title: string;
}

export const columns: any[] = [
    { col_name: 'profile_pic_url', title: '  Profile' },
    { col_name: 'id', title: 'ID' },
    { col_name: 'payroll_id', title: 'Payroll ID' },
    { col_name: 'title', title: 'Title' },
    { col_name: 'first_name', title: 'First Name' },
    { col_name: 'last_name', title: 'Last Name' },
    { col_name: 'age', title: 'Age' },
    { col_name: 'birthdate', title: 'Birth Date' },
    //{ col_name: 'birthplace', title: 'Birth Place' },
    { col_name: 'date_added', title: 'Entry Date' },
    { col_name: 'email_address', title: 'Email' },
    { col_name: 'home_phone_no', title: 'Home Phone' },
    { col_name: 'mobile_phone_no', title: 'Mobile Phone' },
    { col_name: 'work_phone_no', title: 'Work Phone' },
    { col_name: 'address_a', title: 'Address' },
    { col_name: 'address_b', title: 'Address' },
    { col_name: 'suburb', title: 'Suburb' },
    { col_name: 'state', title: 'State' },
    { col_name: 'post_code', title: 'Postal' },
    { col_name: 'branch_name', title: 'Branch' },
    { col_name: 'gender', title: 'Gender' },
    { col_name: 'preferred_name', title: 'Nickname' },
    { col_name: 'type', title: 'Type' },
    { col_name: 'job_type', title: 'Job Type' },
    { col_name: 'job_description', title: 'Job Description' },
    { col_name: 'tasks_performed', title: 'Tasks Performed' },
    { col_name: 'employment_type', title: 'Employment' },
    { col_name: 'status', title: 'Status' },
    { col_name: 'interests', title: 'Interests' },
    { col_name: 'hobbies', title: 'Hobbies' },
    { col_name: 'skills', title: 'Skills' },
    { col_name: 'smokers', title: 'Smokers' },
    { col_name: 'allergies', title: 'Allergies' },
    { col_name: 'on_hold', title: 'On Hold' },
    { col_name: 'volunteer', title: 'Volunteer' },
    { col_name: 'member', title: 'Member' },
    { col_name: 'hourly_rate', title: 'Hourly Rate' },
    { col_name: 'pay_travel_time', title: 'Pay Travel Time' },
    { col_name: 'pay_travel_mileage', title: 'Pay Travel Mileage' },
    { col_name: 'travel_distance', title: 'Travel Distance' },
    { col_name: 'travel_time', title: 'Travel Time' },
    { col_name: 'emergency_contact_email', title: 'Emergency Contact Email' },
    { col_name: 'emergency_contact_name', title: 'Emergency Contact Name' },
    { col_name: 'emergency_contact_relationship', title: 'Emergency Contact Relationship' },  
    { col_name: 'employee_position_display_name', title: 'Position' },  
    { col_name: 'status', title: 'Status' },  
];

export const selectedColumns: string[] =  [
  'title',
  'first_name',
  'last_name',

  'branch_name',
  'job_type',
  'employment_type',
  'job_type',
  'employee_position_display_name',

  'age',
  'birthdate',
  'mobile_phone_no',
  'email_address',
  'address_a',
  'suburb',
  'state',
  'post_code',
  'smokers',
  'status',
];
 